name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go binary
        run: go build -o geos-backend ./Cmd
      
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: geos-backend
          path: geos-backend
  
  transfer_code:
    runs-on: ubuntu-latest
    needs: build
    steps:    
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: geos-backend            
      - name: Copy to bastion
        run: |
          echo "${{ secrets.GEOS_BASTION_KEY_PAIR }}" > key.pem
          chmod 600 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem geos-backend ubuntu@98.93.212.175:/home/ubuntu/
      - name: SSH to Bastion and COPY app-server
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@100.53.237.237 \
            "ssh -o StrictHostKeyChecking=no -i ~/.ssh/geos_app_server.pem ubuntu@10.5.2.206 'sudo systemctl stop geos-backend' && \
             scp -o StrictHostKeyChecking=no -i ~/.ssh/geos_app_server.pem /home/ubuntu/geos-backend ubuntu@10.5.2.206:/var/www/geos-backend && \
             ssh -o StrictHostKeyChecking=no -i ~/.ssh/geos_app_server.pem ubuntu@10.5.2.206 'sudo systemctl restart geos-backend'"
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@100.53.237.237  \
            "ssh -o StrictHostKeyChecking=no -i ~/.ssh/geos_app_server.pem ubuntu@10.5.4.183 'sudo systemctl stop geos-backend' && \
             scp -o StrictHostKeyChecking=no -i ~/.ssh/geos_app_server.pem /home/ubuntu/geos-backend ubuntu@10.5.4.183:/var/www/geos-backend && \
             ssh -o StrictHostKeyChecking=no -i ~/.ssh/geos_app_server.pem ubuntu@10.5.4.183 'sudo systemctl restart geos-backend'"
